# Generated by Django 4.1.13 on 2025-04-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.PositiveIntegerField(unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone_Number', models.BigIntegerField(unique=True)),
                ('Postal', models.IntegerField(default='000000')),
                ('Address', models.CharField(max_length=50)),
                ('User', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=12)),
                ('Role', models.CharField(choices=[('defaultuser', 'Usuario'), ('admin', 'Administrador'), ('worker', 'Trabajador'), ('provider', 'Proveedor')], default='worker', max_length=20)),
            ],
        ),
    ]
